version: '3.8'

services:

  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: "always"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tofi
    command: ["./entrypoint.sh"]
    volumes:
      - .:/tofi/
    env_file:
      - ./docker.env
    environment:
      - DJANGO_SUPERUSER_EMAIL=${DB_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DB_SUPERUSER_PASSWORD}
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: "always"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    expose:
      - 6379





volumes:
  postgres_data:
    driver: local