# Generated by Django 4.2.7 on 2023-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_deposit_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pending_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
