# Generated by Django 4.2.7 on 2023-11-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_card_is_deposit_allowed_card_pending_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('U', 'USD'), ('B', 'BYN')], max_length=1)),
                ('card_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('status', models.CharField(max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payments', to='accounts.card')),
            ],
        ),
    ]
