# Generated by Django 4.2.7 on 2023-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='Test', max_length=20),
        ),
    ]
