# Generated by Django 4.2.7 on 2023-12-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_card_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deposit_pending',
            field=models.BooleanField(default=False),
        ),
    ]
