# Generated by Django 4.2.7 on 2023-12-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_payment_status_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deposit_pending',
            field=models.BooleanField(default=False),
        ),
    ]
