# Generated by Django 4.2.7 on 2023-12-03 11:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_savingsgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='goal_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 12, 3))]),
        ),
    ]
