# Generated by Django 4.2.7 on 2023-12-03 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_savingsgoal_goal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
