# Generated by Django 4.2.7 on 2023-12-05 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_savingsgoal_approved_alter_savingsgoal_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
