# Generated by Django 4.2.7 on 2023-12-05 12:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_savingsgoal_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 4))]),
        ),
    ]
