# Generated by Django 4.2.7 on 2023-12-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_savingsgoal_target_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
    ]
