# Generated by Django 4.2.7 on 2023-12-06 13:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_userbankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 5))]),
        ),
    ]
