# Generated by Django 4.2.7 on 2023-12-07 21:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_savingsgoal_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 6))]),
        ),
        migrations.DeleteModel(
            name='UserAim',
        ),
    ]
