# Generated by Django 4.2.7 on 2023-12-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_savingsgoal_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
